# -*- coding: utf-8 -*-
"""Desafio 2

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1B4QfPSd7Bukidg5a9043tPp68rkGiZeg
"""

"""
tenha como entrada dois números e exiba a sua divisão. Lembre-se 
que não é possível dividir por 0!

"""

n1 = int(input("Digite um numerador: "))
d2 = int(input("Digite um denominador: ")) 

if d2 != 0:
   print(n1/d2) 

else:
   print("Não é possível dividir por 0!")

"""
Ler uma nota de 0 à 10 de um aluno. Caso o usuário digite um 
valor inválido, mostrar a mensagem: "Nota inválida! Digite um 
valor de 0 à 10!"

"""

nota= float(input("Digite o valor de uma nota: "))


if (nota <10) and (nota >0):
  print("A nota do aluno é" , nota)

else:
  print("Nota inválida. Digite um numero de 0 a 10!")

"""
leia um número e mostre se ele é positivo ou negativo ou zero.

"""

n1 = float(input("Digite um numero: "))

if n1 >0:
  print("Positivo!")

elif n1 <0:
  print("Negativo!")

else:
  print("Zero!")

"""
Ler 3 valores e escrever o maior deles

"""

valor1 = int(input("Digite o primeiro valor: "))
valor2 = int(input("Digite o segundo valor: "))
valor3 = int(input("Digite o terceiro valor: "))

maior = valor1

if valor2 > maior:
  maior = valor2

if valor3 > maior:
  maior = valor3

else: 
  print("Maior:" , maior)

##nível médio
"""
As maçãs de um mercado custam R$ 1,30 cada se forem compradas 
menos de uma dúzia, e R$ 1,00 se forem compradas pelo menos 12. 
Escreva um programa que leia o número de maçãs compradas, calcule 
e escreva o custo total da compra.

"""

qtd_macas = int(input("Digite a quantidade de macas compradas: "))

if qtd_macas >0 and qtd_macas <12:
   preco = 1.30

else:
     preco = 1.00 

print("O valor total é de R$:", qtd_macas*preco)

nt_avaliacao1 = float(input("Digite o valor da nota 1: "))
nt_avaliacao2 = float(input("Digite o valor da nota 2: ")) 
media = (nt_avaliacao1+nt_avaliacao2) / 2 

if media >=6:
  print("Aprovado. Media: ", media)

else:
  print("Reprovado. Media: ", media)

"""
A jornada de trabalho mensal de um funcionário na empresa X é de 
160 horas. O funcionário que trabalhar mais de 160 horas receberá 
hora extra, cujo cálculo é o valor da hora regular com um 
acréscimo de 50%. Escreva um algoritmo que leia o número de horas 
trabalhadas em um mês, o salário por hora e escreva o salário 
total do funcionário, que deverá ser acrescido das horas extras, 
caso tenham sido trabalhadas.

"""

horas = int(input("Digite a quantidade de horas trabalhadas no mes: "))
salario_hora = float(input("Digite o valor da hora: "))

if horas > 160:
   horas_extras = horas - 160
   salario_hora_extra = salario_hora + salario_hora * 0.5
   salario = 160 * salario_hora + horas_extras * salario_hora_extra
   print("O salario total é de R$", salario)

else:
   salario = horas*salario_hora
   print("O salario total é de R$", salario)

##Nivel Avançado

entrada1 = int(input("Digite a quantidade de apitos: "))

if entrada1 >0 and entrada1 <2:
  print("Atualização de DRAM")
elif entrada1 ==2:
  print("Circuito de Paridade")
elif entrada1 >2 and entrada1 <4:
  print("Memória Base 64K RAM")
elif entrada1 >3 and entrada1 <5:
  print("Timer do Sistema")
elif entrada1 ==5:
  print("Processador")
else:
  print("Erro desconhecido.")

"""
. leia uma nota de um aluno, de 0 à 10 e mostre na tela o seu 
conceito. Considere: 
nota >= 9,0 -> Excelente
>= 7,0 e < 9,0 -> Bom
>= 5,0 e < 7,0 -> Razoável
< 5,0 -> Fraco

"""

aluno1 = int(input("Digite a sua nota: "))

if aluno1 >=9.0:
  print("Excelente!")
elif aluno1 >= 7.00 and aluno1 <9.00:
  print("Bom!")
elif aluno1 >=5.00 and aluno1 <7.00:
  print("Razoavel!")
elif aluno1 <5.00:
  print("Fraco!")

"""
Escreva na tela “Boa Madrugada”, “Bom dia”, “Boa tarde” ou “Boa 
noite” dependendo da hora do dia que o usuário digitar no 
teclado. Caso a hora seja inválida mostre: “Erro. Hora inválida”. 
Opcional: mostre uma imagem diferente para cada alternativa

"""

hora = int(input("Digite a hora desejada: "))

if hora >=00 and hora <=5:
  print("Boa Madrugada")  
elif hora >=6 and hora <=11:
  print("Bom dia!")
elif hora >=12 and hora <=18:
  print("Boa tarde!")
elif hora >=19 and hora <=23:
  print("Boa noite!")

else:
  print("Hora invalida")