# -*- coding: utf-8 -*-
"""Desafio 3

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Nwza1_dws-ljDo1XyVeHnxCPGgKiA-t6
"""

"""
1- Desenvolva todos os exercícios verificando os dados lidos do teclado, não permitindo valores inválidos. Caso sejam inválidos, repita a leitura até que seja correta:
a. leia do teclado as dimensões de um retângulo (base e altura), calcular e escrever a área do retângulo. (Valores inválidos: 0 e números negativos).

"""

b = -1
a = -1
while b <= 0:
  b = float(input("Digite a dimensão da base: "))
  if b <= 0:
    print("dimensões invalidas")
while a <= 0:
  a = float(input("Digite a dimensão da altura: "))
  if a <= 0:
    print("dimensões invalidas")

area = b*a
print("O calculo da area do retangulo é: ", area, "cm")

"""
leia do teclado o número total de eleitores de um município, o número de votos brancos, nulos e válidos. 
Calcular e escrever o percentual que cada um representa em relação ao total de eleitores. (Valores inválidos: números negativos).

"""
eleitores, votos_brancos, votos_nulos, votos_validos = -1,-1,-1,-1
while eleitores < 0:
  eleitores = int(input("Digite a quantidade de eleitores: "))
  if eleitores < 0:
    print("Valor inválido.")
while votos_brancos < 0:
  votos_brancos = int(input("Digite a quantidade de votos em branco: "))
  if votos_brancos < 0:
   print("Valor inválido.")
while votos_nulos < 0:
  votos_nulos = int(input("Digite a quantidade de votos nulos: "))
  if votos_nulos < 0:
    print("Valor inválido.")
while votos_validos < 0:
  votos_validos = int(input("Digite a quantidade de votos válidos: "))
  if votos_validos < 0:
    print("Valor inválido.")
    
percb = votos_brancos / eleitores
print("Votos em branco: ", percb*100, "%")
percn = votos_nulos / eleitores 
print("Votos nulos:", percn*100, "%")
percv = votos_validos / eleitores 
print("Votos validos: ", percv*100, "%")

""""
Leia 2 números e mostre o maior e o menor. (Valores inválidos: números menores que -99 e maiores que 99).

"""

num1 = int(input("Digite um numero: "))
while num1 <= -99 or num1 > 99:
    print("Valor invalido")
    num1 = int(input("Digite um numero: "))
num2 = int(input("Digite outro numero: "))
while num2 <= -99 or num2 > 99:
   print("Valor invalido")
   num2 = int(input("Digite um numero: "))
if num1 > num2:
  maior = num1
  menor = num2
else:
  maior = num2
  menor = num1
print("O maior numero é:", maior, "e o menor numero é:", menor)

##Nivel medio

"""
Desenvolva todos os exercícios verificando os dados lidos do teclado, não permitindo valores inválidos. Caso sejam inválidos, repita a leitura até que seja correta:
a. leia do teclado uma distância em quilômetros e mostre na tela o seu valor convertido em metros. (Valores inválidos: números negativos).
"""
km = float(input("Digite a distancia em quilometros: "))
while km < 0:
  print("Valor inválido.")
  km = float(input("Digite a distancia em quilometros:"))
metros = km * 1000
print(km, "km em metros é", metros, "m.")

"""
b. leia do teclado uma distância em metros e mostre na tela o seu valor convertido em quilômetros.(Valores inválidos: números negativos).
"""

metros = float(input("Digite a distancia em metros: "))
while metros < 0:
  print("Valor invalido.")
  metros = float(input("Digite a distancia em metros: "))
km = metros / 1000
print(metros, "A distancia em km é", km, "km")

"""
Crie um código utilizando LAÇO WHILE:
a. Enquanto a1=0 for menor que 5, incrementando 1 a cada laço, mostre na tela o seu número.
"""

a1 = 0
while a1 < 5:
  print(a1)
  a1 += 1
for a1 in range(0,5,+1):
  print(a1)

"""

b. Enquanto a2=0 for menor que 3, incrementando 1 a cada laço, mostre na tela o seu número multiplicado por 10.
"""

a2 = 0
while a2 < 3:
  print(a2)
  a2 +=1
for a2 in range(0,3,+1):
  print(a2*10)

"""
c. Enquanto a3=20 for maior que 10, decrementando 1 a cada laço, mostre na tela o seu número.
"""

a3 = 20
while a3 > 10:
  print (a3)
  a3 -=1
for a3 in range(20,10,-1):
  print(a3)

"""
d. Para a4=0 enquanto a4 menor que 10, incrementando 1, mostre na tela o seu número
"""

a4 = 0
while a4 < 10:
  print(a4)
  a4 +=1
for a4 in range(0,10,+1):
  print(a4)

"""
a. leia 3 valores (A, B e C) representando as medidas de um triângulo. Mostrar se tais medidas formam um triângulo ou não. 
Lembre-se que o valor de cada lado deve ser menor que a soma dos outros 2 lados e deve ser maior que o valor absoluto da diferença entre os outros 2 lados.
| B - C | < A < B + C
| A - C | < B < A + C
| A - B | < C < A + B
"""

"""
leia do teclado uma temperatura em graus Fahrenheit e mostre na tela o seu valor convertido em Celsius. 
Lembrando que (c/5) = (f-32)/9. (Valores inválidos: menores que -457,69).
"""

grausf = float(input("Digite a temperatura em Fahrenheit: "))
celsius = ((grausf - 32) / 9) * 5
while grausf < -457.69:
  print("Temperatura inválida.")
  grausf = float(input("Digite a temperatura em Fahrenheit: "))
print("A temperatura de", grausf, "Fº convertida em Celsius é de", celsius,"Cº.")

"""
leia do teclado uma temperatura em graus Celsius e mostre na tela o seu valor convertido em Kelvin. 
Lembrando que 0 grau Kelvin = -273,15 Celsius.(Valores inválidos: números negativos).

"""

celsius = float(input("Digite a temperatura em graus Celsius: "))
kelvin = 273.15
while celsius < 0: 
  print("Temperatura inválida.")
  celsius = float(input("Digite a temperatura em graus Celsius: "))
print("A temperatura de", celsius, "Cº convertida em Kelvin é de", kelvin + celsius)

"""
Para a7=0 enquanto a7 menor que 10, incrementando 1, insira um outro while aninhado internamente contendo para a8=0 até a8 menor que 10, incrementando 1, mostre na tela "(a7,a8)".
"""

a7 = 0
a8 = 0
while a7 < 10:
  print(a7)
  a7 +=1
  while a8 < 10:
    print(a8)
    a8 += 1 
  for a8 in range(0,10,+1):
    print(a8)
print(a7,a8)

"""
Para a6=10 enquanto a6 maior ou igual a 0, decrementando 1, mostre na tela o seu número.
"""

a6 = 10
while a6 >= 0:
  print (a6)
  a6 -=1
for a6 in range(10,0,-1):
  print(a6)

"""
Para a5=0 enquanto a5 menor ou igual a 10, incrementando 1, mostre na tela o seu número multiplicado por 10.

"""

a5 = 0
while a5 <= 10:
  print(a5)
  a5 +=1
for a5 in range(0,10,+1):
  print(a5*10)

"""
Faça um código utilizando qualquer recurso que você aprendeu até agora para:
a. Mostrar na tela todos os números pares de 0 à 1000
"""

for num in range(0,1001):
  if num % 2 == 0:
    print(num)

"""
b. Mostrar na tela todos os números ímpares de 5 à 55
"""

for num in range(5,56):
  if num % 2 == 1:
    print(num)

"""
c. Mostrar na tela somente números primos de 2 à 100;
"""

for n in range(2,101):
  primo = True
  for i in range(2, int(n/2)):
    if n % i == 0: 
      primo = False
      break
  if primo:
    print(n)